name: test

on: pull_request

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
  
      - name: Run tox -e lint
        run: tox
        env: 
          TOXENV: lint

  test:
    name: unittests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toxenv:
            - py36-dj111-wag23
            - py36-dj20-wag23
        include:
          - toxenv: py36-dj111-wag23
            python-version: 3.6
          - toxenv: py36-dj20-wag23
            python-version: 3.6

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coveralls

      - name: Run tox -e ${{ matrix.toxenv }}
        run: |
            tox -e ${{ matrix.toxenv }}
            coveralls
        env: 
          TOXENV: ${{ matrix.toxenv }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          DJANGO_SETTINGS_MODULE: teachers_digital_platform.tests.settings

      - name: Prepare test coverage
        if: matrix.toxenv == 'py36-dj111-wag23'
        run: coverage xml

      - name: Store test coverage
        # Submit coverage from our prefered tox run only
        if: matrix.toxenv == 'py36-dj111-wag23'
        uses: actions/upload-artifact@v1
        with:
          name: unittest_coverage
          path: ./coverage.xml

  coverage:
    runs-on: ubuntu-latest
    needs:
      - unittests

    steps:
      - uses: actions/checkout@v1
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coveralls

      - name: Retrieve unittest coverage
        uses: actions/download-artifact@v1
        with:
          name: unittest_coverage

      - name: Check unittest coverage
        run: |
          diff-cover unittest_coverage/coverage.xml --fail-under=100
