name: unittest

on: pull_request

jobs:

  unittest:
    runs-on: ubuntu-latest

    services:
      postgres:
        # https://help.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers
        # https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
        image: postgres
        env:
          POSTGRES_USER: cfpb
          POSTGRES_PASSWORD: cfpb
          POSTGRES_DB: cfgov
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      # - run: git fetch --prune --unshallow  # Fetch all history for all tags and branches. Works on GH, doesn't work locally.
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*  # Fetch all tags. # Doesn't fetch the necessary intermediate commits.
      # - run: git fetch origin master  # Fetch the entire master branch. Hopefully this combined with the fetching of tags will be sufficient.
      - run: git fetch origin ${{ github.base_ref }} && git checkout ${{ github.base_ref }}  # Fetch and checkout the PR branch

      - run: git describe --tags --long --dirty  # This has to run successfully for setuptools-git-version to eventually work

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
        env:
          RUNNER_TEMP: /tmp

      - name: Install Node dependencies
        run: |
          npm install -g gulp-cli jest
          npm config set package-lock false
          npm install

      - name: Run front-end tests
        run: npm test

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run back-end tests
        run: |
          rm -rf /github/workspace/.tox/
          tox
